### ISSUE TITLE
`SHOW DATABASES` does not tally with current connection

### ISSUE THREAD

**Issue by bilogic** [dbcodeio/public#21] opened 2024-09-18 06:36 UTC
![image](https://github.com/user-attachments/assets/51c66db1-025c-4e3f-a176-eb3b7207fafe)

I think this is a high priority bug..

I'm connected to `114-local`, you can see a long list of databases. 
I `Create a new SQL file` and run `SHOW DATABASES;`, to my horror, the databases I see are from connection `112-ops`... imagine if I did a drop.

Also, is stripe the only payment method? It kept declining my card.

**Comment by mikeburgh** [comment] 2024-09-18 13:18
Yes that is a serious issue.

Are you able to reproduce it ? The new sql file, did you select a connection for it, or open it from the link in the explorer ?

Can you share the configs for the two connections from settings json ?

**Comment by bilogic** [comment] 2024-09-18 13:52
```
"dbcode.connections": [
    {
        "connectionId": "ffVMtKUUUSQ0M8pRUXMJ5",
        "name": "112-ops",
        "driver": "mysql",
        "color": "#F00019",
        "connectionType": "host",
        "host": "x.y.z.112",
        "port": 3306,
        "ssl": false,
        "username": "aaaaa",
        "password": "",
        "savePassword": "secretStorage",
        "tunnelId": "",
        "database": "",
        "connectionTimeout": 30
    },
    {
        "connectionId": "74FSR5rRmwpIGIPzo0jud",
        "name": "114-local",
        "driver": "mysql",
        "connectionType": "host",
        "host": "x.y.z.114",
        "port": 3306,
        "ssl": false,
        "username": "bbbbb",
        "password": "",
        "savePassword": "secretStorage",
        "tunnelId": "",
        "database": "",
        "connectionTimeout": 30
    },
    {
        "connectionId": "Y4TztuboJnwGk8fgwd55N",
        "name": "113",
        "driver": "mysql",
        "connectionType": "host",
        "host": "127.0.0.1",
        "port": 3306,
        "ssl": false,
        "username": "ccccc",
        "password": "ccccc",
        "savePassword": "yes",
        "tunnelId": "",
        "database": "",
        "connectionTimeout": 30,
        "driverOptions": {
            "retrievePublickey": true
        }
    }
],
```
i have redact parts of it

**Comment by bilogic** [comment] 2024-09-18 13:55
I can't reproduce it now.

**Comment by mikeburgh** [comment] 2024-09-18 13:56
Thanks, no worries on the redaction, it was mainly the ids I wanted to see to make sure they were unique…. 

As that’s the only way I could see this happening (manually editing the json and copying configs and not changing ids) which I will add a check for.

how did you open the sql file, or rather how did you tell it the connection to use ?

**Comment by bilogic** [comment] 2024-09-18 14:04
You have an icon `Create a new SQL file` beside the the database.
I clicked on 114's database to run `show databases`, but it show the list from 112.

**Comment by bilogic** [comment] 2024-09-18 14:27
![image](https://github.com/user-attachments/assets/e7352b2d-4594-4730-8044-9683d24319cf)

![image](https://github.com/user-attachments/assets/8efa7414-61f4-425f-a6b7-7974b643e07d)

I have a few VSCode, I switched back to the one that exhibit the issue, basically reproducible.

**Comment by bilogic** [comment] 2024-09-18 14:31
I'm opening the SQL editor using this icon
![image](https://github.com/user-attachments/assets/dd4c0cc6-9fb6-45ad-abbb-d9ca1929ffc1)

**Comment by mikeburgh** [comment] 2024-09-18 14:36
I see the issue…

those results are form the database client extension… not dbcode.

you have both extensions running, not sure how it’s mapped to a connection but it executed the statement and shows its results (dbcode results appear in the panel near terminal not an editor tab). 

I am still going to implement the fix for duplicate ids and might move up the profile feature (will let you set a profile like production or dev for a connection, and then if it’s say production you get a warning before any destructive operations… delete, update, drop etc)

I will look into payment methods and get back to you

**Comment by mikeburgh** [comment] 2024-09-19 17:39
A check for duplicate connection ids that could occur through manual settings editing is now in place (version 1.2.5), not that it was the cause of this, but good to make sure it does not happen as it could lead to incorrect connections being opened.

I sent you an email on the payment options, let me know if you did not get it. Closing this issue now.

**Comment by bilogic** [comment] 2024-09-20 12:48
Thanks, sorted out the payment already.

**Closed** 2024-09-23 21:53 UTC
