### ISSUE TITLE
Postgres connections become hanging / stuck after a while

### ISSUE THREAD

**Issue by tymonTe** [dbcodeio/public#125] opened 2024-11-28 07:58 UTC
Hi

First of all, congrats on creating the best SQL extension for VS code, it is really solild and I switched from DataGrip 👏

I'm facing an issue where queries randomly get stuck, the timer is running but I never get a result. This is for simple queries that usually evaluate in milliseconds.
![Image](https://github.com/user-attachments/assets/73d00bf6-3849-434f-a904-4399a20ca460)

Latest version of Postgres via GCP cloud SQL.
The same issue occurs when: doubleclicking a table, running a .sql file, running a cell in a .dbcnb file. 
Things that don't work: 
* clicking cancel -> has no effect. 
* closing and opening the file -> no effect
* disconnecting and re-connecting to the database -> no effect

The only thing that recovers from this error is quitting and restarting the IDE

Worth noting that the issue is not with the database connection, as the app I'm building is still able to connect while Dbcode is stuck.
Any ideas how I can troubleshoot this? 🙏

Best regards,
Tymon

**Comment by tymonTe** [comment] 2024-11-29 10:23
hi
Thanks for your quick reply 🙂

This is how it looks like with devtools open. Nothing is being logged. 
Is there a way to restart the postgres driver without restarting the entire IDE? 🤔 

![Image](https://github.com/user-attachments/assets/746e0834-5d0b-4358-9567-5107bbae72af)

**Comment by mikeburgh** [comment] 2024-11-29 13:58
Thanks!

If you right click on the connection in the db explorer and choose disconnect it will close and  destroy the driver, and a when you then reconnect open a new one.

I am working on a release now with some a potential fix and some more debugging to hopefully track this down.

Will update when it’s released

**Comment by mikeburgh** [comment] 2024-12-02 20:51
I just pushed 1.4.13 which has two potential fixes for this, along with a fix for closing executing tabs via the x on the tab. <br><br>Can you try it out and let me know if it fixes your PG issues.

I have still not been able to replicate it, so not sure what the cause is… I tried in google's cloud to no avail. Are you using Alloy or regular Postgres in google ?

**Comment by mikeburgh** [comment] 2024-12-11 00:14
Just following up to see if this is still happening ?

**Comment by tymonTe** [comment] 2024-12-13 09:39
I didn't have the issue in a while, thank you! 👍💪

**Closed** 2024-12-13 16:31 UTC
Labels: awaiting feedback
