### ISSUE TITLE
Failed to unpack libSQL Binary. Error: terminated

### ISSUE THREAD

**Issue by emilienbidet** [dbcodeio/public#22] opened 2024-09-23 09:53 UTC
This morning I tried DBCode with my Turso libsql database and it doesn't works when trying to open the database.

I get the VS code error:

`Failed to unpack libSQL Binary. Error: terminated`

**Comment by mikeburgh** [comment] 2024-09-23 15:31
Thanks for submitting this issue.

For some of the drivers that are native, we need to download them based on your operating system and architecture when you first try and use the driver, which is what it was doing but something terminated the decompress step.

can you try uninstalling and re installing the extension? If it gets terminated again, which operating system are you using ?

**Comment by mikeburgh** [comment] 2024-10-07 16:33
I am closing this, re open it if the issue is still happening and we can dig into it

**Closed by mikeburgh** 2024-10-07 16:33 UTC
