### ISSUE TITLE
Error when connecting to OLD MySQL

### ISSUE THREAD

**Issue by nike1v** [dbcodeio/public#11] opened 2024-07-10 11:54 UTC
VSCode error text:
Error introspecting database aida, error: (conn:25, no: 1064, SQLState: 42000) You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'tables AS (
    SELECT table_schema
                        ,table_name as table' at line 1
sql: WITH tables AS (
    SELECT table_schema
                        ,table_name as table_id
			,table_name
			,table_type
			,TABLE_ROWS
			,DATA_LENGTH as data_bytes
			,INDEX_LENGTH as index_bytes
			,table_comment as comment
    FROM information_schema.tab... - parameters:[]

MySQL version:
"MYSQL_MAJOR=5.7",
"MYSQL_VERSION=5.7.44-1.el7",
"MYSQL_SHELL_VERSION=8.0.35-1.el7"

Using username & password connection. DB located in docker container.
I'd like to be able to connect to my DB.
Upgrading version is not possible.

**Comment by mikeburgh** [comment] 2024-07-10 16:59
At the moment version 5.7 is not supported, as we use JSON features it does not have. However you should have got a message about that rather than the error.

What do you get when you run this on the database: 

select version(), @@GLOBAL.version_comment

**Comment by nike1v** [comment] 2024-07-11 14:46
Here is the response:
+-----------+------------------------------+
| version() | @@GLOBAL.version_comment     |
+-----------+------------------------------+
| 5.7.44    | MySQL Community Server (GPL) |
+-----------+------------------------------+
1 row in set (0.01 sec)

**Comment by nike1v** [comment] 2024-07-11 14:47
The docker is running via this image:
# Use the official MySQL 5.7 image
FROM mysql:5.7

**Comment by mikeburgh** [comment] 2024-07-15 22:25
Thank you for your help. 

I discovered that MySQL version 5.7 doesn't support common table expressions (CTEs) and window functions. We modified the introspection code for version 5.7, and it's been released in version 0.15.1. 

Let me know how you go, and if you find any other issues with 5.7

**Comment by mikeburgh** [comment] 2024-07-31 01:34
Yeah so I looked into this.. it's in the mysql database,  I assume you have that DB on the server.. Can you grant the user you are connecting with access to that database, I don't believe it needs to be all privileges.

**Comment by nike1v** [comment] 2024-08-01 19:33
I have checked it twice, the user with what I'm trying to connect have access to the desired db as well as I granted access for the innodb_index_stats too. But still have this issue. I can connect with the same user to the database via phpmyadmin or other products which supports connecting to mysql. 
How can I help you find the issue?

**Comment by mikeburgh** [comment] 2024-08-01 20:32
Apprecaite your willingness to working on getting it figured out.

Here is the main part of the introspection script for 5.7.. try running this on the database as the same user, and see if you get any errors..

```sql
CREATE TEMPORARY TABLE dbc_tmp_columns
select table_schema
        ,table_name
        ,-1 as column_id 
        ,column_name
        ,ordinal_position
        ,data_type
        ,case when COLUMN_KEY = 'PRI' then true else false end as primaryKey
        ,Case when IS_NULLABLE = 'YES' then true else false end as is_nullable 
        ,case when generation_expression != '' then true else false end as is_generated
        ,GENERATION_EXPRESSION as generation_expression
        ,character_maximum_length as max_length
        ,NUMERIC_PRECISION as "precision"
        ,numeric_scale as scale
        ,column_default
        ,COLUMN_COMMENT as comment
FROM information_schema.columns
where table_schema = DATABASE();

CREATE TEMPORARY TABLE dbc_tmp_indexes
SELECT s.TABLE_SCHEMA
        ,s.TABLE_NAME
        ,s.INDEX_NAME
        ,Case when s.NON_UNIQUE = 1 then false else true end as is_unique
        ,Case when s.Index_name = 'PRIMARY' then true else false end as is_primary_key
        ,Case when s.Index_name = 'PRIMARY' then true else false end as is_clustered
        ,s.INDEX_COMMENT as comment
        ,SUM(stat_value * @@innodb_page_size) as data_bytes
FROM INFORMATION_SCHEMA.STATISTICS s
JOIN mysql.innodb_index_stats iis on ( iis.database_name = TABLE_SCHEMA and iis.table_name = s.table_name and iis.stat_name = 'size')
WHERE s.table_schema = DATABASE()
GROUP BY 1,2,3,4,5,6,7;

CREATE TEMPORARY TABLE dbc_tmp_foreign_keys
SELECT CONSTRAINT_SCHEMA as table_schema
        ,CONSTRAINT_NAME as index_name
        ,TABLE_NAME as table_name 
        ,REFERENCED_TABLE_NAME as referenced_table_name
FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS
WHERE CONSTRAINT_SCHEMA = DATABASE();
```

You can take out the temp tables if you want, they are just there to work around limits with our approach in 5.7.. but you can see in the 2nd select, the join on the index_stats table.. which is what the error you provided indicated was the issue with select permissions.

**Comment by nike1v** [comment] 2024-08-02 15:00
The result of your query is the same that I sent in the previous comment. User do not have access to the mysql.innodb_index_stats in line where you're trying to JOIN it.
To fix it I had to manually run SQL: GRANT SELECT ON mysql.innodb_index_stats TO 'user'@'%';
Then the SQL you  provided works.
Looks like it's because I'm connecting as non-root user to the database, so that user do not have any permissions to the mysql tables.

**Comment by mikeburgh** [comment] 2024-08-02 15:25
So now you granted access, it should work in the app ?

We will look at options to re work this to see if we can identify permissions ahead of the introspection and fall back if they are not inplace

**Comment by nike1v** [comment] 2024-08-02 15:33
Yes, it does work in the app now after I connected as a root user and granted the permission to my current user.

**Comment by mikeburgh** [comment] 2024-08-29 17:22
We just published 1.1.3, which removes the requirement to connect as a user with root privileges, or one that has been granted access to innodb_index_stats.

**Comment by lancelotly** [comment] 2024-09-23 15:18
Error introspecting database , error: Access denied for user 'user'@'%' to database 'db'

I'm also doing a non-root user on mysql 5.7.36 
:(
---
VSCode Version: 1.92.2
Extension Version: 1.2.5
OS: linux
Arch: x64

**Comment by mikeburgh** [comment] 2024-09-23 15:35
Ohh and thanks for posting this on the existing issue rather than opening a new one, appreciated!

**Comment by lancelotly** [comment] 2024-09-23 17:36
> I thought we cleaned up all the non root user issues, maybe not.
> 
> are you able to open any other databases on the severe or do they all fail with introspection ?
> 
> This error seems to indicate the user you are logging in as does not have any database access at all, the previous non root user issues where when we were trying to read data from some of the system tables that non root users do not have access to

<img width="230" alt="image" src="https://github.com/user-attachments/assets/566a061b-0daa-4109-92b6-dd8bb26bff88">

I could open database A on the connection, but not for database B (which pops the error).
Just running `SHOW GRANTS FOR CURRENT_USER();` it shows:

```
GRANT USAGE ON *.* TO 'user'@'%'
GRANT ALL PRIVILEGES ON `A`.* TO 'user'@'%'
GRANT SELECT, INSERT ON `B`.* TO 'user'@'%'
```

**Comment by mikeburgh** [comment] 2024-09-24 18:29
Thanks for the grant details.. So the issue is the revised 5.7 introspection I added uses temp tables to store the various details we need before returning the data... but that requires the CREATE permissions on the DB.

Looking to see if there is another way to work around that..

**Comment by mikeburgh** [comment] 2024-09-24 21:40
Can you check out version 1.2.6, I reworked the introspection to not use temp tables, a lot more verbose, but will now work with just select permissions.

**Comment by lancelotly** [comment] 2024-09-25 02:47
> Can you check out version 1.2.6, I reworked the introspection to not use temp tables, a lot more verbose, but will now work with just select permissions.

Confirm that it can access to the limited permission DB. 👍

I can execute queries directly in my sql file now. However, it seems to take forever to load the tables in the CONNECTIONS side panel. Anyway, the database B can be accessed in version 1.2.6.

(Probably the database B is too large? db A shows 4GB and db B is 20+GB...)

:D

**Comment by mikeburgh** [comment] 2024-09-25 03:10
Good news on getting the introspection sorted.

When you say it's slow, do you mean when you expand the list of tables ? Or when you click on a table and it opens in a new tab ?

The first time you connect to a database, the extension introspects it, and that lets us show the tree in the connections window (tables, views, etc) among other features (autocomplete)..

The size of the database wont really effect the speed of that, more so the amount of tables, views, procs, etc that might be in the database...  The first time it may feel slow, but once we do it once we then cache it, and next time you connect, we show the cache and refresh it in the background.. so it will feel much faster. 

To get 5.7 to work, we also had to be a bit repetitive since we cannot use CTE's or create temp tables (given the chance someone has permission only for select like you have setup), and this probably slowed it down for you compared to when you first opened db A on 5.7. 

If you disconnect and re connect the server and open db B again you should find it's now much faster (and in the background once it finishes the introspection it will update the tree with any changes).

If it's when opening a table (double clicking it) that will totally depend on the data in the table (number of columns) and how long that takes to transfer from your server to your computer.. by default we limit it to loading 100,000 rows, but you can change that by right clicking the table, or editing the max rows setting.

**Closed** 2024-10-04 03:25 UTC
